export const authTypes = {
  EMAIL_CHANGED: "EMAIL_CHANGED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  CLEAN_AUTH_FORM: "CLEAN_AUTH_FORM",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",
  LOGIN_USER: "LOGIN_USER",
  SIGNOUT_USER: "SIGNOUT_USER",
};

export const employeeTypes = {
  EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
  CLEAN_EMPLOYEE_FORM: "CLEAN_EMPLOYEE_FORM",
  EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
  EMPLOYEES_FETCH_SUCCESS: "EMPLOYEES_FETCH_SUCCESS",
  SELECTED_EMPLOYEE: "SELECTED_EMPLOYEE",
};
